### ISSUE TITLE
Remove the explicit source features

### ISSUE THREAD

**Issue by pcdavid** [eclipse-emfservices/emf-validation#21]
With modern versions of Tycho & PDE it seems that there is no real need to define them explicitly.
See https://www.eclipse.org/lists/cross-project-issues-dev/msg19553.html

**Comment by sratz** [comment]
This change did a bit too much.

It's not necessary to **define** the feature manually - letting Tycho's `feature-source` do that is fine, but the auto-generated feature still has to be put in the repository.

The changes to [releng/org.eclipse.emf.validation.repository/category.xml](https://github.com/eclipse-emfservices/emf-validation/commit/b0a3e9e9e8a4fdcdb95c8c62b28096d9dac6f698#diff-deab37c4fc82c6e9c7e1f88a40240bc1aca2efaf775d5fb31e246bc47a3a2d90) should be reverted.

**Comment by pcdavid** [comment]
My reading from [the message on cross-project](https://www.eclipse.org/lists/cross-project-issues-dev/msg19553.html) was that source *bundles* are enough, as in then end only bundles have actual meaninful sources, and whichever way they (the bundles) are made available in the build or developement environment, their coresponding source bundle, if available, will be found/resolved.

> the idea is to get rid of source features.
> [...]
> source features are not so important artifacts per se, what really matters is making source bundles available [...] nowadays, none of those do require source features
> [...]
> you may be able to get rid of source features 

What am I missing?

**Comment by pcdavid** [comment]
I have no issue with re-introducing them (see the new PR), but I'd like to understand why they are needed.

**Comment by sratz** [comment]
Well it depends on the way the features are modeled and what you want to provide.

1. You could have the individual bundles only and not include them in any feature
2. You could include the source bundles in your `.sdk` feature
3. You could ship a dedicated `.source` feature collecting all the source bundles

The issue is in 1.13.0 option 3 was chosen, so removing them was simply a breaking change for consumers of that `.source` feature. E.g, we were/are including them in our `.target` definition for our product and this suddenly broke with Eclipse SimRel 2024-09 M3 containing EMF services 1.14.0 RC1.

Therefore, for compatibility, the feature should be kept published on the update site.

**Comment by sratz** [comment]
Same applies to emf-transaction: https://github.com/eclipse-emfservices/emf-transaction/commit/0dc611547c12bc60babfc94935325b24b92d8ea8#diff-6952ff2471471abf34549768c483cb1debd81a8dabca03fd0fb03f2ef40b69e3

**Comment by pcdavid** [comment]
Should be fixed by ccb21dbb7cbfb0ee7ae29cc9b063040f9b948e1f.

**Comment by pcdavid** [comment]
> Same applies to emf-transaction: [eclipse-emfservices/emf-transaction@0dc6115#diff-6952ff2471471abf34549768c483cb1debd81a8dabca03fd0fb03f2ef40b69e3](https://github.com/eclipse-emfservices/emf-transaction/commit/0dc611547c12bc60babfc94935325b24b92d8ea8#diff-6952ff2471471abf34549768c483cb1debd81a8dabca03fd0fb03f2ef40b69e3)

Fixed by https://github.com/eclipse-emfservices/emf-transaction/commit/c857cbf97cac28a06f9716b0bf6f36ab2d4dc897

**Comment by pcdavid** [comment]
FYI, modern Tycho (5.0.2) is making it clear that source features are deprecated.

```
[WARNING]  Goal 'feature-source' is deprecated: Source features are used for a long time to include sources in development environments but they where always brittle to use and badly integrated. As nowadays Tycho/P2 offers better ways to archive similar, the automatic generation of such features is deprecated and will be removed on the next release. In cases where this is still required, one should replace it with an explicitly maintained source feature in a dedicated module.
```

The consensus is to remove them, source *bundles* are present resolvable in all contexts that matter. See https://github.com/eclipse-simrel/simrel.build/issues/1171.

The upcoming versions of EMF Validation (v1.14.2) and EMF Transaction (v1.14.3) for Eclipse 2026-06 will *remove source features*. Note that EMF Validation & Transaction are in maintenance mode, with few actual code changes (if any) in new versions. The only actual change in these upcoming versions is the move to JUnit 5 for tests (as JUnit 3.x is also slowly on its way out).  If you can not or do not want to update your build, you can continue to consume the older releases, they are not going anywhere and you will not miss any new feature.
